### PR TITLE
Confirmation page

### PR DESCRIPTION
**Pull request by harrisj**
This is still a WIP, since I need to update the tests I broke (I know, bad Jake!). But it's a start on the confirmation screen. It does something a little unconventional with the PlaceBid object to dry run validation for the confirmation screen, but I think this is better than other approaches. Also, I fixed the button issues with the Submit / Cancel buttons

### CODE REVIEW

**Comment by allalala** [comment]
@harrisj can you add a screenshot of what this looks like on your local machine?

**Comment by harrisj** [comment]
micro-purchase

**Comment by harrisj** [comment]
Marking this as a WIP no longer since its tests now pass.

**Comment by adelevie** [comment]
nice! I shall review!

**Comment by adelevie** [comment]
looks phenomenal to me :dragon_face:

**Pull request merged**
