### PR TITLE
Use rails12factor gem to ensure assets are served

### PR DESCRIPTION
**Pull request by adelevie**

### CODE REVIEW

**Comment by baccigalupi** [comment]
Can we add asset compilation to the deploy build process? It is not a good idea to check in the compiled assets because they change so often. It bloats the git repository, but also keeps the change log from clearly showing what has changed.

**Comment by adelevie** [comment]
This gem might already handle that. I'll delete the contents of public/assets, and re-push to see if it works.

**Comment by adelevie** [comment]
It works.

**Comment by blacktm** [comment]
:ship:

**Pull request merged**
