### PR TITLE
Add small rake task for updating github user data

### PR DESCRIPTION
**Pull request by jessieay**
* Closes https://github.com/18F/micropurchase/issues/959

### CODE REVIEW

**Comment by jessieay** [comment]
code climate failure on here is weird -- not liking commented code!

**Comment by jessieay** [comment]
tested this one manually and it worked...I am comfortable with that since it's a one-off task...do we think we need automated tests?

**Comment by harrisj** [comment]
I think it's fine to not hve tests, but can we have the # lines consistently indented?

**Comment by jessieay** [comment]
@harrisj updated!

**Comment by harrisj** [comment]
LGTM! Merging!

**Pull request merged**
