### PR TITLE
Move some JS to vendor/assets

### PR DESCRIPTION
**Pull request by harrisj**
Also, added an explicit codeclimate.yml file.

Do not merge yet. I want to test this with an `cf push` from my machine before it gets merged into develop or anything.

### CODE REVIEW

**Comment by gemfarmer** [comment]
@harrisj looks great, but it isn't running locally for me. Are there other commands that you ran locally to make it work?

**Comment by gemfarmer** [comment]
@harrisj also, [c3.css](https://github.com/18F/micropurchase/blob/develop/app/assets/stylesheets/source/c3.css) can be moved to `vendor/assets/stylesheets/.

**Comment by stvnrlly** [comment]
Feel free to pull in my linting in the `js-linter` branch here, or I can continue that branch once this is merged.

**Comment by harrisj** [comment]
Oh my bad, @stvnrlly. Can we just merge this and rebase your branch?

**Comment by stvnrlly** [comment]
Definitely, and that's sort of what I was expecting to do. I can take care of all of that post-merge.

**Pull request merged**
