### PR TITLE
Failing spec for who won features on auction page. [WIP]

### PR DESCRIPTION
**Pull request by adelevie**
acceptance criteria:

```ruby
  scenario "Viewing auction page for a closed auction" do
    create_closed_auction
    auction = Presenter::Auction.new(@auction)
    visit auction_bids_path(auction.id)

    expect(page).to have_content("Winning Bid (#{auction.current_bidder.name}):")
    expect(page).not_to have_content("Current Bid:")

    expect(page).to have_content("Auction ended at:")
    expect(page).not_to have_content("Bid deadline:")
  end

  scenario "Viewing auction page for a closed auction with no bidders" do
    create_closed_bidless_auction
    auction = Presenter::Auction.new(@auction)
    visit auction_bids_path(auction.id)

    expect(page).to have_content("Auction ended with no bids.")
    expect(page).not_to have_content("Current Bid:")

    expect(page).to have_content("Auction ended at:")
    expect(page).not_to have_content("Bid deadline:")
  end
```

### CODE REVIEW

**Comment by adelevie** [comment]
@harrisj could/should this be closed in favor of https://github.com/18F/micropurchase/pull/170 ?

**Comment by harrisj** [comment]
Ha, you wrote my scenarios for me! Let me merge in and see if I can get it all working now. Thank you!

**Comment by adelevie** [comment]
_whoah_

**Comment by adelevie** [comment]
I'll close this issue and use some git-fu to get the code here into your PR.

**Comment by adelevie** [comment]
(don't delete the branch!)

**Pull request closed without merging**
