### PR TITLE
Don't show bid button if auction is over

### PR DESCRIPTION
**Pull request by cscairns**

### CODE REVIEW

**Comment by allalala** [comment]
Thank you for this PR @cscairns!

**Comment by harrisj** [comment]
Let me know if you want an overview about how some of these classes are organized, because it's a little unusual if you are used to a conventional Rails app

**Comment by cscairns** [comment]
thx @harrisj...i'm picking it up as a work through some dev items...how presenters and viewmodels are being used within the context of this app are a little new to me (e.g., the presenters actually seem more like decorators)

**Comment by jessieay** [comment]
This problem was solved elsewhere. Closing!

see https://18f.slack.com/archives/micropurchase/p1461013049000182 for more details

**Pull request closed without merging**
