### PR TITLE
Users list in admin panel

### PR DESCRIPTION
**Pull request by adelevie**
Acceptance criteria:

```ruby
    visit "/admin/users"
    expect(page).not_to have_text('must be an admin')
    user = Presenter::User.new(@user)

    expect(page).to have_text(user.duns_number)
    expect(page).to have_text(user.email)
    expect(page).to have_text(user.name)
    expect(page).to have_text(user.github_id)
```

### CODE REVIEW

**Comment by adelevie** [comment]
Listing page:
screen shot 2015-12-16 at 4 01 13 pm
Clicking on the Github ID gets you this helpful JSON:
screen shot 2015-12-16 at 4 01 29 pm

**Comment by vzvenyach** [comment]
What's the url? Surely it's not /admin/auctions, right?

**Comment by adelevie** [comment]
/admin/users

**Comment by adelevie** [comment]
Bad typo on my part tbqh

**Comment by harrisj** [comment]
One question I have (and maybe this is something @baccigalupi has an opinion on), but the routes.rb currently defines a bunch of routes that might not ever be implemented (like `DELETE` of a user): 

```
            Prefix Verb   URI Pattern                              Controller#Action
              root GET    /                                        auctions#index
      auction_bids GET    /auctions/:auction_id/bids(.:format)     bids#index
                   POST   /auctions/:auction_id/bids(.:format)     bids#create
   new_auction_bid GET    /auctions/:auction_id/bids/new(.:format) bids#new
          auctions GET    /auctions(.:format)                      auctions#index
           auction GET    /auctions/:id(.:format)                  auctions#show
              bids GET    /bids(.:format)                          bids#index
           my_bids GET    /my-bids(.:format)                       bids#my_bids
         edit_user GET    /users/:id/edit(.:format)                users#edit
              user PATCH  /users/:id(.:format)                     users#update
                   PUT    /users/:id(.:format)                     users#update
    admin_auctions GET    /admin/auctions(.:format)                admin/auctions#index
                   POST   /admin/auctions(.:format)                admin/auctions#create
 new_admin_auction GET    /admin/auctions/new(.:format)            admin/auctions#new
edit_admin_auction GET    /admin/auctions/:id/edit(.:format)       admin/auctions#edit
     admin_auction GET    /admin/auctions/:id(.:format)            admin/auctions#show
                   PATCH  /admin/auctions/:id(.:format)            admin/auctions#update
                   PUT    /admin/auctions/:id(.:format)            admin/auctions#update
                   DELETE /admin/auctions/:id(.:format)            admin/auctions#destroy
       admin_users GET    /admin/users(.:format)                   admin/users#index
                   POST   /admin/users(.:format)                   admin/users#create
    new_admin_user GET    /admin/users/new(.:format)               admin/users#new
   edit_admin_user GET    /admin/users/:id/edit(.:format)          admin/users#edit
        admin_user GET    /admin/users/:id(.:format)               admin/users#show
                   PATCH  /admin/users/:id(.:format)               admin/users#update
                   PUT    /admin/users/:id(.:format)               admin/users#update
                   DELETE /admin/users/:id(.:format)               admin/users#destroy
                   GET    /auth/:provider/callback(.:format)       authentications#create
             login GET    /login(.:format)                         logins#index
            logout GET    /logout(.:format)                        authentications#destroy
```

These routes will trigger 500s if accessed, but do we care they are there? We could put conditions on the `resources :users` declarations and such but is that worth it?

**Comment by harrisj** [comment]
Going to merge. If we want to deal with the routes issue above we can try a new PR

**Pull request merged**
