### PR TITLE
Cache hero metrics in a table

### LINKED ISSUE #1040: Site is crashing/performing very slowly
I suspect this is partially due to the `/insights` page.

From @jessieay:

```
app.crash {"instance"=>"[redacted]", "index"=>0, "exit_status"=>255, "exit_description"=>"out of memory", "reason"=>"CRASHED"}
```

### PR DESCRIPTION
**Pull request by jessieay**
* Closes #1040

### CODE REVIEW

**Comment by jessieay** [comment]
this is another CC error related to class length :(

**Comment by adelevie** [comment]
It's pretty compact. Shrinking the class can probably only be done with silly code golf, which would make things harder to read.

**Comment by jessieay** [comment]
cool -- I am going to open a separate PR to up our class limit in rubocop -- 150 sound reasonable?

**Comment by adelevie** [comment]
150 seems good!

**Pull request merged**
