### PR TITLE
Style edits

### PR DESCRIPTION
**Pull request by awfrancisco**

### CODE REVIEW

**Comment by adelevie** [comment]
I'm good with this. What say you, @baccigalupi, @blacktm, or @vzvenyach? (I'll also rebase).

**Comment by adelevie** [comment]
rebased

**Comment by blacktm** [comment]
These look good. We also have more UI/UX changes coming in #60, FYI.

**Comment by awfrancisco** [comment]
@blacktm Cool. I can take a look at that copy when it's ready/up.

**Comment by blacktm** [comment]
@awfrancisco That'd be great. The mockup images are here, feel free to add comments: https://github.com/18F/micropurchase/issues/60

**Comment by adelevie** [comment]
Thanks, @awfrancisco!

**Pull request merged**
