### PR TITLE
Add skills chart on the insights page

### PR DESCRIPTION
**Pull request by jessieay**
* Closes https://github.com/18F/micropurchase/issues/836
* Replaces donut chart made from static data that we were using before

screen shot 2016-07-12 at 5 09 56 pm

### CODE REVIEW

**Comment by harrisj** [comment]
Looks fine, but CodeClimate is super annoyed. Do you want to look those over and see if any of them make sense to fix?

**Comment by jessieay** [comment]
@harrisj yes will attempt to fix now!

**Comment by jessieay** [comment]
ok @harrisj cleaned it up -- not sure I can eliminate final two CC failures

**Comment by harrisj** [comment]
Eh, we'll fix them all some day. Merging...

**Pull request merged**
