### PR TITLE
Winners page

### PR DESCRIPTION
**Pull request by gemfarmer**
For [Previous Winners Trello Ticket](https://trello.com/c/DvU4RlrH/119-previous-winners-page)

What does this PR do?
* adds two pages: 
  * `/auctions/winners`, which houses site metrics and will serve as a marketing tool for the site.
  * `/auctions/winners/archive`, a list of all past projects, filterable by "accepted" and "rejected"

---------------

* [x] get feedback on usability/understandability of graphs
* [x] confine script to this page (bundle like [this](http://blog.seancarpenter.net/2012/11/05/page-specific-javascript-with-the-asset-pipeline/))
* [x] winners page archive
  * [x] selector/filter

Notes: 
* I have shelved "success rate" and "total vendors" until I better know how to approach it
* I have shelved project by type (bug, feature,etc) until we have data for it
* I manually determined language for each repo. This should have data so that we can use it

Notes (updated):
~~* One failure is unrelated to the changeset~~
* I have ditched (commented out) the auctions by bids by date (chart 3). It was cumbersome and hard to interpret.
* squashed commits
* I replaced it with an easier to follow bubble chart. Thanks @ddotrollins 
* I still have not made the viz scripts page specific. I can do that, but it doesn't seem to be majorly impacting performance, so maybe it could be done in a different issue.
* Could I get some eyes on this? @adelevie @harrisj @lauraGgit @vzvenyach @allalala @stvnrlly   The copy is still all lorem ipsum. 
screen shot 2016-04-01 at 3 49 49 pm
screen shot 2016-04-01 at 3 50 05 pm
screen shot 2016-04-01 at 3 50 16 pm

### CODE REVIEW

**Comment by harrisj** [comment]
This might not be an effect of this branch, but I am seeing some weird footer spacing on Chrome 18f_-_micro-purchase

**Comment by vzvenyach** [comment]
So cool

**Comment by gemfarmer** [comment]
@harrisj The footer spacing is [a known, separate](https://github.com/18F/micropurchase/issues/344) issue that I'm going to get to. As for wiring it up, I think it should wire up fine once [this line](https://github.com/18F/micropurchase/blob/winners-page/app/assets/javascripts/winners/previousWinners.js#L785) is removed and it is drawing data directly from the API. Or did you mean something else?

**Comment by stvnrlly** [comment]
It looks like the closeness of 3/7 and 3/8 are causing funkiness in the `Community` graph. 

I'm also not sure what the `Bids by auction` one is showing: is the size of the circle the winning bid amount? The legend at the bottom is throwing me off.

**Comment by gemfarmer** [comment]
@stvnrlly thanks for the response. For `Community`, the closeness of 3/7 and 3/8 are definitely confusing. This could possibly be fixed by showing just the last month (so that the ticks are farther apart) and allowing for a pan-and-zoom option so that people can see farther back if they want to.

For `Bid by auction` the circle size is `Winning bid amount`. The legend is a bit confusing. The point of having it there is so that users can toggle points on/off, but maybe that isn't important. At the very least I should probably through on an `Auction #` label.

**Comment by adelevie** [comment]
Sadly, we're going to need to revert this. While there were no detectable issues when running this locally or on Travis, there is a Rails Asset Pipeline issue that I believe is being caused by the backticks in files like `app/assets/javascripts/winners/previousWinners.js`.

We'll merge the PR back in once one of the following is done:

- Figure out why the Rails Asset Pipeline (in production) fails when running into these backticks
- Use the old interpolation method (e.g by converting the backticks into a series of `"`s and `+`s ... sorry, @gemfarmer if this is annoying :/) )

Deploy error: https://travis-ci.org/18F/micropurchase/builds/121214935#L1251

**Pull request merged**
