### PR TITLE
Fix a broken link_to that was rendering wrong

### LINKED ISSUE #1443: User object being instantiated in Closed auctions view for undelivered auctions
localhost_3000_admin_auctions_closed

### PR DESCRIPTION
**Pull request by harrisj**
Fixes #1443

### CODE REVIEW

**Comment by adelevie** [comment]
merging when :green:

**Comment by baccigalupi** [comment]
Sorry, didn't realize these were connected. @adelevie knows the coding standards better, so you should go with his pass.

**Comment by harrisj** [comment]
No need to apologize! Our cucumber tests aren't so great at looking at page details (Capybara isn't so great either), so it's a bit annoying to test at the feature level, especially since that missed it here

**Comment by baccigalupi** [comment]
@harrisj So one of the use cases for view models is to ensure that there is no logic in your view. That would include deriving a url. I know this isn't a typical Rails way, but the benefit is that you could create a unit test on the view model for this kind of a bug.

**Comment by harrisj** [comment]
I hear you on the View Models, and we have used them for some things like conditional branching, but I wasn't sure about using them for URL construction. But we could make this change

**Comment by harrisj** [comment]
I think this change to use ViewModels for app construction should wait for future refactoring

**Pull request merged**
