### PR TITLE
Validate format of DUNs number

### PR DESCRIPTION
**Pull request by jessieay**
* Use samwise to validate format
* Validate that it contains only integers

https://github.com/18F/micropurchase/issues/425

### CODE REVIEW

**Comment by jessieay** [comment]
former PR for this feature: https://github.com/18F/micropurchase/pull/438

**Comment by harrisj** [comment]
Argh, Github, you're killing me today with all the merge conflicts

**Comment by jessieay** [comment]
@harrisj rebased!

**Comment by harrisj** [comment]
Looks good to me, merging

**Pull request merged**
