### PR TITLE
Fix winners page (I hope!)

### PR DESCRIPTION
**Pull request by jessieay**
* On staging, winners page works
* On prod, it is broken
* https://micropurchase.18f.gov/assets/source/c3.css does not exist
* but https://micropurchase-staging.18f.gov/assets/source/c3.css does
* We should not be directly referencing static assets -- hellooooo we
  are using rails and we <3 the asset pipeline
* Renaming `c3.css` to `c3.scss` makes it so we are putting it in asset
  pipeline
* I don't understand why this is the case, but confirmed behavior by
  compiling assets locally
* The other changes here are config cleanup

### CODE REVIEW

**Comment by harrisj** [comment]
So, can you test this works okay by doing a manual cf push to staging?

**Comment by jessieay** [comment]
@harrisj sure, I also tested that it works locally by using compiled assets locally

**Comment by jessieay** [comment]
you still want me to test on staging before we merge?

**Comment by jessieay** [comment]
pushed to staging and everything looks goood https://micropurchase-staging.18f.gov/auctions/winners

**Comment by harrisj** [comment]
Rails' asset pipeline: "You have bested me, but I shall have my revenge!"

**Pull request merged**
