### PR TITLE
Updated FE tweaks in the CSS files and HTML

### PR DESCRIPTION
**Pull request by ddotrollins**

### CODE REVIEW

**Comment by harrisj** [comment]
Rebased from master and fixed a few failing tests

**Comment by adelevie** [comment]
Nice. Is there a way to re-target this to `develop` instead of `master`?

**Comment by harrisj** [comment]
I think we have to close and create a new one. Are we doing that switch now?

**Comment by adelevie** [comment]
Yeah, let's try that.

**Comment by harrisj** [comment]
Going to close this and reopen against `develop`

**Pull request closed without merging**
