### PR TITLE
JSON schema specs

### PR DESCRIPTION
**Pull request by pkarman**

### CODE REVIEW

**Comment by jessieay** [comment]
@pkarman there's a CI failure here - want to update? should I take over?

**Comment by pkarman** [comment]
@jessieay the test is intentionally failing. this was in response to https://18f.slack.com/archives/dev/p1456254837000302 and the preceding conversation.

**Comment by jessieay** [comment]
@adelevie what do you want to do with this?

**Comment by adelevie** [comment]
I'm ok with closing and prioritizing some sort of improvement/fix to the way we use json schema.

**Comment by jessieay** [comment]
ok created an issue that references this PR so we can prioritize working on this tech debt item https://github.com/18F/micropurchase/issues/437

**Pull request closed without merging**
