### PR TITLE
Do not check SAM on each login

### PR DESCRIPTION
**Pull request by jessieay**
* We already check each time DUNs is updated, why check on login?

### CODE REVIEW

**Comment by harrisj** [comment]
To provide some context, this was implemented before we decided to have a DelayedJob and cron checking SAM.

**Comment by jessieay** [comment]
@harrisj should we still do it? we could throw a delay on there. not sure if SAM status changes regularly or not

**Comment by harrisj** [comment]
No, we can get rid of it. If we are doing the other mechanism, we might as well just use one. I just wanted to provide some context.

**Comment by harrisj** [comment]
Looks good to me. Merging

**Pull request merged**
