### PR TITLE
Set smarter defaults for start, end, delivery dates

### PR DESCRIPTION
**Pull request by jessieay**
* Closes https://github.com/18F/micropurchase/issues/914

screen shot 2016-07-22 at 5 19 35 pm

### CODE REVIEW

**Comment by harrisj** [comment]
> Freezing immutable objects is pointless.

Harsh, CodeClimate. Don't you judge us! (but let's fix those anyway)

**Comment by harrisj** [comment]
Looks good but can we clean up some of the CodeClimate issues about freezing numbers?

**Comment by jessieay** [comment]
@harrisj fixed! thanks for the review

**Comment by harrisj** [comment]
LGTM. Merging!

**Pull request merged**
