### PR TITLE
Add metric for Sam.gov vendors to winners page

### PR DESCRIPTION
**Pull request by jessieay**
* Closes https://github.com/18F/micropurchase/issues/706

### CODE REVIEW

**Comment by jessieay** [comment]
@harrisj same code climate sadness

**Comment by adelevie** [comment]
LGTM, merging after CC is happy.

**Comment by jessieay** [comment]
@adelevie not sure if I can make CC happy - ideas?

**Comment by adelevie** [comment]
semicolons? ok good point ... merging ...

**Pull request merged**
