### PR TITLE
Front end fixes

### PR DESCRIPTION
**Pull request by gemfarmer**
:sun_with_face: [P R E V I E W](https://fkocnmgbtk.localtunnel.me) :sun_with_face: 

What does this PR do?

- broke apart existing stylesheets into a new css architecture that includes: 
  - uswds variables stylesheets
  - uswds overrides (grid and general) stylesheets
  - `core`, `components`, `blocks`
  - Removed as much unnecessary code as possible
- Visual style
  - refined typography for the site
  - refined color palette, drawing on USWDS and 18F Branding for colors
  - added new 18F Branding logos
  - Added some font icons
  - updated responsive layout
- Redid header
- added accessible (ARIA) dropdown (for larger screens)
- added accessible (ARIA) drawer (for small screens)
- Updated rspec tests to accommodate new html
- Added responsive table to details view

What this did not do:
- **fine tune admin-side**

screen shot 2016-03-11 at 10 04 40 am
screen shot 2016-03-11 at 10 04 57 am

Details view:
screen shot 2016-03-11 at 10 05 09 am

### CODE REVIEW

**Comment by gemfarmer** [comment]
@allalala what needs to be done to ensure that this can be merged?

**Comment by allalala** [comment]
@gemfarmer this needs a :+1: from @adelevie, who will then merge. 

IMHO, this looks great. Thank you!

**Comment by gemfarmer** [comment]
@allalala cool. He had said that it looked good, but I'm not sure it was a go-ahead.

**Comment by gemfarmer** [comment]
@adelevie does this have your seal of approval to merge?

**Comment by adelevie** [comment]
reviewing this today. Sorry for the delay!

**Comment by gemfarmer** [comment]
Thanks! and no worries.

**Comment by harrisj** [comment]
I'd prioritize this ahead of #303, which I will rebase

**Comment by adelevie** [comment]
@gemfarmer do you mind if I squash this into a single commit (or into a few commits)?

**Comment by gemfarmer** [comment]
@adelevie squash away!

**Comment by adelevie** [comment]
@harrisj, this PR pulls in the web design standards into the `assets` folder. Is this correct, or should this be handled by the gem?

**Comment by adelevie** [comment]
Closing in favor of https://github.com/18F/micropurchase/pull/341

Thanks @gemfarmer :trumpet:

**Pull request closed without merging**
