### PR TITLE
WIP: Consolidate view models for auction admin status

### PR DESCRIPTION
**Pull request by harrisj**
Following the suggestion in #1167, this is an effort to clean up logic and consolidate the AuctionAdminStatusPresenter and BidStatusPresenter view models into one place.

The rough plan of work is as follows:

- [X] AdminAuctionStatusPresenter::Future -> BidStatusPresenter::Future::Admin
- [X] AdminAuctionStatusPresenter::WorkInProgress -> BidStatusPresenter::Over::Admin::WorkInProgress
- [x] AdminAuctionStatusPresenter::PendingAcceptance -> BidStatusPresenter::Over::Admin::PendingAcceptance
- [x] AdminAuctionStatusPresenter::Accepted -> BidStatusPresenter::Over::Admin::Accepted
- [x] AdminAuctionStatusPresenter::Rejected -> BidStatusPresenter::Over::Admin::Rejected
- [ ] Remove AdminAuctionStatusPresenterFactory

The end game is to remove the AdminAuctionStatusPresenter hierachy and its Factory entirely (although we might rename it a C2StatusFactory or something). This makes it a little clear what is wear and makes it so the factory for BidStatusPresenter mirrors our matrix of supported states

### CODE REVIEW

**Comment by jessieay** [comment]
I wonder if we should consolidate these a bit less or differently. 

The way I've been doing it in the past is:

`BidStatusPresenter` is the namespace for anything that the person (guest/admin/vendor) sees on the public auctions#show page
`C2StatusPresenter` is for what the admin seeds on admin/auctions#show
`AdminAuctionStatus` is for what the admin sees on admin/auctions#show when not related to C2

Maybe we keep two namespaces to clarify what is for the admin-only view and what is for the regular show page (even though some of those statuses are specific to admins) ?

The one exception to this is that we now have one view, (the "unpublish" button view) that is for both the regular auctions#show page and for the admin/auctions#show page. I think it would be good to share logic between those but still have them in separate namespaces.

**Comment by harrisj** [comment]
Ooops, I suppose I should read things before I go ahead on this. I don't know how I feel on this one, is it better to have one ginormous factory so you can see exactly how complex it is or to try a bunch of specific factories (where we would probably also have a different one for guests)

**Comment by jessieay** [comment]
to be clear, we still have two giant factories after this PR, they are just returning presenters in the same namespace rather than view-specific namespaces.

**Comment by harrisj** [comment]
I see, so it seems like I should start over perhaps and try a different approach. That makes sense but I would like to figure out if we can rename C2Status -> AuctionAdminStatus at least. Suggestions?

**Comment by harrisj** [comment]
Deprecating in favor of #1199

**Pull request closed without merging**
