### PR TITLE
Include unique bidders per auction on winners page

### PR DESCRIPTION
**Pull request by jessieay**
* Look at completed auctions
* Closes https://github.com/18F/micropurchase/issues/564

### CODE REVIEW

**Comment by harrisj** [comment]
CodeClimate isn't happy but it's looking good to me

**Comment by jessieay** [comment]
@harrisj just made that class that a bit more compact in afe615a -- fingers crossed!

**Comment by jessieay** [comment]
@harrisj argh code climate still mad but I think this is about as good as I am gonna get on this one. Unless you have some ideas for me?

**Comment by harrisj** [comment]
Yeah, let's let it slide for now. Merging.

**Pull request merged**
