### PR TITLE
Updating logo & footer

### PR DESCRIPTION
**Pull request by jenniferthibault**
Greetings! This reverts to the official 18F logo and removes the "18F" text in the footer. The logo you were using was just an early experiment which didn't actually go anywhere, I just happened to see this site as part of the collection that uses the US web design standards.

screen shot 2015-11-09 at 7 04 14 pm

screen shot 2015-11-09 at 8 00 12 pm

### CODE REVIEW

**Comment by jenniferthibault** [comment]
@adelevie I don't think this patch would cause travis to fail itself—maybe a heads up for you all that something is up with travis? But this is ready for review

**Comment by adelevie** [comment]
I think this one's on us as well. Thanks for the PR! We had a brief development pause, but we should resume sometime this week and get everything straightened out.

**Comment by adelevie** [comment]
Tests pass locally:

```
➜  micropurchase git:(updating-logo) bundle exec rake spec
/home/adelevie/.rbenv/versions/2.2.3/bin/ruby -I/home/adelevie/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib:/home/adelevie/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-support-3.3.0/lib /home/adelevie/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
...............................................................

Finished in 0.86421 seconds (files took 1.55 seconds to load)
63 examples, 0 failures
```

**Comment by adelevie** [comment]
Thanks @jenniferthibault!

**Comment by jenniferthibault** [comment]
Hey @adelevie just checking back and I'm not seeing the changes on the live site. Any idea what's up?

**Comment by adelevie** [comment]
None of this has been deployed. I am working on fixing our continuous
deployment pipeline. However, we are actively merging these fixes into the
`master` branch.

On Tue, Nov 17, 2015 at 5:32 PM, Jennifer Thibault <notifications@github.com

**Comment by jenniferthibault** [comment]
Oh! My GitHub n00bness is showing, I thought that merging into the master branch was the same as deploying. Thank you! :)

**Comment by adelevie** [comment]
Merge to master usually does deploy to production. Our issue, not yours :)

On Tue, Nov 17, 2015 at 5:36 PM, Jennifer Thibault <notifications@github.com

**Pull request merged**
