### PR TITLE
Deploy 1/14/16 #1

### PR DESCRIPTION
**Pull request by adelevie**
- fixes a link that should have been html and not markdown
- API MVP

#### Authentication

Set the following headers:

- `Accept` -> `text/x-json`
- `Api-Key` -> `your api key`

The API is a GitHub Personal Access Token (get one here: https://github.com/settings/tokens). Uncheck all the before you create it.

#### Methods:

GET `/admin/users`

GET, POST, PUT `/admin/auctions`

All responses are in json.

### CODE REVIEW

**Comment by adelevie** [comment]
Don't merge it! Don't do it! Not until we get the asset pipeline stuff figured out!

Don't do it!

**Comment by maya** [comment]
@adelevie see: https://github.com/18F/micropurchase/pull/237#discussion_r49679354

**Comment by adelevie** [comment]
Thanks, @maya. Is this adversely affecting the asset pipeline?

**Comment by maya** [comment]
@adelevie No, it's unrelated to that.

**Pull request merged**
