### PR TITLE
Refactor bid status to make it MOAR awesome

### PR DESCRIPTION
**Pull request by jessieay**
* Use one method to return bid partial or bid status partial

### CODE REVIEW

**Comment by adelevie** [comment]
LGTM @jessieay. Needs rebase. I can review again after that.

**Comment by jessieay** [comment]
@adelevie  rebased!

**Comment by adelevie** [comment]
Excellent! Ignore or heed the CodeClimate warnings? One of them is annoying (109 lines > 100 line limit).

**Comment by jessieay** [comment]
hmmm I am not sure if I can make that class smaller. Ideas?

**Comment by adelevie** [comment]
Is there a way to get CC to run again with the new rules merged in? Or just merge anyway?

**Comment by jessieay** [comment]
sure, I can rebase and re-push

**Comment by adelevie** [comment]
ok!

**Comment by jessieay** [comment]
@adelevie 🍏

**Pull request merged**
