### PR TITLE
Admin can associate skills with an auction

### PR DESCRIPTION
**Pull request by jessieay**
* Closes https://github.com/18F/micropurchase/issues/834

screen shot 2016-07-11 at 12 13 24 pm

### CODE REVIEW

**Comment by harrisj** [comment]
This looks good, but how are we handling skill creation. Do we need an admin for that (as a PR) or are we just inserting in the console?

**Comment by harrisj** [comment]
LGTM. Merging

**Comment by jessieay** [comment]
@harrisj great call will ping michael about that

**Comment by mtorres253** [comment]
I can add stories for that.

On Mon, Jul 11, 2016 at 3:35 PM, Jacob Harris <notifications@github.com>
wrote:

> This looks good, but how are we handling skill creation. Do we need an
> admin for that (as a PR) or are we just inserting in the console?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/micropurchase/pull/848#issuecomment-231886429>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAGHNVDwZTAPOqm22nobidc332zHFnc9ks5qUsVPgaJpZM4JJsNz>
> .
>



-- 
Michael Torres
Product Lead, Micropurchase Platform
18F
(415) 920-3205

**Pull request merged**
