### PR TITLE
Submit feedback link

### PR DESCRIPTION
**Pull request by adelevie**
Acceptance criteria
```ruby
  scenario "Viewing the home page" do
    visit "/"
    expect(page).to have_content("Submit Feedback")
  end
```

### CODE REVIEW

**Comment by adelevie** [comment]
feedback

**Comment by adelevie** [comment]
Links to https://docs.google.com/forms/d/15ycigLrTS7Ld4iVPgIMN-U5dMDFy6TnrHGOSkgk7qTI/viewform?c=0&w=1

**Comment by harrisj** [comment]
I'm happy with this. I know we are planning to restyle down the road, and I'd like to make this look a bit prettier then.

**Comment by adelevie** [comment]
Great! I'm adding a few other links per @allalala's request and should be ready after the next commit.

**Comment by adelevie** [comment]
links

**Comment by adelevie** [comment]
I know not everything lines up perfectly, but it is probably good enough to ship for now ... I want to get to the rest of the stories now but we can and should iterate on this further.

**Comment by adelevie** [comment]
Ready to merge if you're good with the code, @harrisj.

**Pull request merged**
