### PR TITLE
Move Timecop out of dev group

### PR DESCRIPTION
**Pull request by jessieay**
* For dev:prime, again

### CODE REVIEW

**Comment by harrisj** [comment]
I am wondering if we want to say `require: false` for it and explicitly require it in the spec_helper and factory_girl auctions definition since I don't think we want to load it on production otherwise?

**Comment by jessieay** [comment]
sure! good idea

**Comment by jessieay** [comment]
Ok so I just tried this out -- problem with adding `require: false` is that then we need to explicitly require these gems in the test env which is kind of a pain.

Then I tried to include them without `require: false` in the test env in addition to listing them outside, I get this error from bundler:

```
Your Gemfile lists the gem timecop (>= 0) more than once.
You should probably keep only one of them.
```

what do you think we should do?

**Comment by harrisj** [comment]
Yeah, we'd have to require explicitly within the rails_helper, the env.rb for cucumber and the dev prime as well. But let's wait on that I guess

**Pull request merged**
