### PR TITLE
Reorganizing the Cucumber Features

### PR DESCRIPTION
**Pull request by harrisj**
Trying for a more granular and descriptive approach where many features are named with a subject-verb-object style and features do not contain as many scenarios. Next step would be reorganizing step definitions

### CODE REVIEW

**Comment by jessieay** [comment]
loving this!

**Comment by harrisj** [comment]
Reorganizing the steps could probably wait for another PR. Let's just focus on how to name/organize these feature files in this PR

**Comment by jessieay** [comment]
Big 👍  from me! Will leave to @adelevie to merge to make sure we're all on the same page with this new naming structure.

**Comment by harrisj** [comment]
I decided to add the Style doc I had shared with all of you on Google Docs (and I edited it a little), but I'm going to hold off on reorganizing the step definitions for another PR if you think that is okay

**Pull request merged**
