### PR TITLE
Added a Presenter::AuctionUser class (and Null model version)

### PR DESCRIPTION
**Pull request by harrisj**
Following the excellent (as usual) advice of @baccigalupi, I added a subsidiary presenter class for cleaning up the user_bids and other methods. In addition, I included a cleanup Kane suggested for the date presenters. Future work to be in other PRs

### CODE REVIEW

**Comment by adelevie** [comment]
@harrisj hate to be a stickler, but what would be a good way to test these? I think all the code is :+1:

**Comment by harrisj** [comment]
I guess I assumed that current tests would cover this refactoring, but I will check on the coverage to be sure.

**Comment by adelevie** [comment]
That's a good point. We can add additional tests, if we decide to, in a later PR.

**Comment by harrisj** [comment]
Well I am about to go check on coverage so I will check

**Pull request merged**
