### PR TITLE
Delivery due at is required field

### PR DESCRIPTION
**Pull request by jessieay**
* There is no way to create an auction without this field via the form
* Removes chance of `nil` errors

### CODE REVIEW

**Comment by harrisj** [comment]
I think the reason why we allowed delivery_due_at to be nil was that we could work on drafts without having to set the time the delivery is due by. Otherwise, there is the temptation to just give it some value so you can save and then forgetting why you set it to that specific date later.

**Comment by jessieay** [comment]
@harrisj yes  I think you are right about that but the way the form is set up now, admins actually cannot set the `delivery_due_at` timestamp to a nil value. So the only nil values we have are from console-created data.

**Comment by harrisj** [comment]
Oh okay. Sometimes I wonder if we should allow people to set the delivery due at as a days offset and then actually evaluate it when the auction is published, but I might be overthinking this

**Comment by harrisj** [comment]
Okay, going to merge then.

**Comment by jessieay** [comment]
@harrisj that is what we do! (kind of -- this is just on the new form, not edit)
screen shot 2016-08-23 at 9 16 28 am

**Comment by harrisj** [comment]
I know we do that, but we evaluate it immediately on save. It's kinda silly, but I sometimes wonder if we should just make end_time and delivery_due_at offsets that we store until the auction is published. Then they become actual datetimes.

**Pull request merged**
