### PR TITLE
Use 18F-wide SCSS linter

### PR DESCRIPTION
**Pull request by jessieay**
* See https://pages.18f.gov/frontend/#css-linting

### CODE REVIEW

**Comment by jessieay** [comment]
Let's ignore violations for now and fix as we go

**Comment by harrisj** [comment]
So, you think we should avoid the 42 violations and fix them later. I'm fine with that

**Comment by jessieay** [comment]
@harrisj yeah I feel like it would be pretty time intensive to fix all our existing CSS, especially deeply nested stuff. But we should def update as we go along and touch files!

**Comment by harrisj** [comment]
I think Hound suggested against correcting all Rubocop issues because you could create new errors in the process and instead just fixing things as you go along. I agree too. Merging.

**Pull request merged**
