### PR TITLE
Admins cannot bid

### PR DESCRIPTION
**Pull request by jessieay**
* Add logic to rules that doesn't allow admins to bid
* Closes https://github.com/18F/micropurchase/issues/995

### CODE REVIEW

**Comment by harrisj** [comment]
Should we have an `admin_bids_on_an_auction.feature`?

**Comment by jessieay** [comment]
@harrisj I prefer to leave negative cases to lower-level unit tests. Mostly so our feature specs can remain smaller in number and our test suite can stay fast

**Comment by jessieay** [comment]
thoughts on that @harrisj  ?

**Comment by harrisj** [comment]
Okay, that works for me. Merging

**Pull request merged**
