### PR TITLE
Update copy and design for sign up page

### PR DESCRIPTION
**Pull request by jessieay**
* Do not merge until we get sign off from @mtorres
* Closes https://github.com/18F/micropurchase/issues/1160

screen shot 2016-09-26 at 4 12 45 pm

### CODE REVIEW

**Comment by harrisj** [comment]
LGTM, but will wait for signoff

**Comment by mtorres253** [comment]
Can you give the big paragraph a width of 90% and margin: auto; Also the spacing should be roughly the same (about 15px) at the top and bottom of the container box.

**Comment by jessieay** [comment]
- top paragraph center aligned
- space between paragraph and container (grey) should be equal
- also make margin equal

**Comment by jessieay** [comment]
Updated at 2761f7e

screen shot 2016-09-27 at 11 03 55 am

this design is now approved by @mtorres253 so this is ready for merge when you are @harrisj

**Comment by harrisj** [comment]
LGTM

**Pull request merged**
