### PR TITLE
More cucumber features from @harrisj

### PR DESCRIPTION
**Pull request by adelevie**
squashed all of @harrisj's commits from https://github.com/18F/micropurchase/pull/303.

### CODE REVIEW

**Comment by harrisj** [comment]
DO NOT MERGE yet. I have to move a few more features from `spec/features` to full-fledged Cucumber `features`

**Comment by baccigalupi** [comment]
Wow massive effort :+1: 

Love that the diff shows about as many additions as removals in lines of code

**Comment by harrisj** [comment]
Any objections to merging this?

**Comment by adelevie** [comment]
no objections! I'll click the big green button. Great work! :ship:

**Pull request merged**
