### PR TITLE
WIP: Fix image assets

### PR DESCRIPTION
**Pull request by harrisj**
This is a fix that uses the [web standards gem tweaks I made](https://github.com/18F/us_web_design_standards_gem/pull/7) to eliminate the need for local copies of images and font CSS. Two notes:

1. It uses a forked copy the web standards gem for now (not cool in long run)
2. **Do not merge** until the web_standards PR is merged

### CODE REVIEW

**Comment by adelevie** [comment]
@harrisj is this still WIP? Want me to rebase?

**Comment by harrisj** [comment]
This is still a WIP until people are happy with the changes I made to the us_web_design_standards_gem, since this PR just eliminates redundant CSS and image files. Please leave it unmerged until then.

**Comment by harrisj** [comment]
This pull request will be made obsolete by whatever work is being done with the big refactor for the US Web Design Standards gem https://github.com/18F/us_web_design_standards_gem/issues/15, recommending we close this PR

**Comment by jessieay** [comment]
+1 to closing and reopening. Do we have a GH issue for this change so we don't forget about it? Just briefly scanned them and didn't see one...

**Comment by jessieay** [comment]
created an issue for this here https://github.com/18F/micropurchase/issues/431

closing!

**Pull request closed without merging**
